import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import AutomatModel from 'App/Models/AutomatModel'

export default class AutomatModelSeeder extends BaseSeeder {
  public async run() {
    await AutomatModel.createMany([
      { name: 'LCM1', automatMarkId: 2 },
      { name: 'Brisa H41', automatMarkId: 10 },
      { name: 'Brisa H70', automatMarkId: 10 },
      { name: 'Brisa H85', automatMarkId: 10 },
      { name: 'Brisa МР Normal', automatMarkId: 10 },
      { name: 'City', automatMarkId: 10 },
      { name: 'City L', automatMarkId: 10 },
      { name: 'City M', automatMarkId: 10 },
      { name: 'Mistral H70', automatMarkId: 10 },
      { name: 'Novara', automatMarkId: 10 },
      { name: 'Palma', automatMarkId: 10 },
      { name: 'Palma H70', automatMarkId: 10 },
      { name: 'Palma H87', automatMarkId: 10 },
      { name: 'Sienna', automatMarkId: 10 },
      { name: 'Tempo ME', automatMarkId: 10 },
      { name: 'Zensia', automatMarkId: 10 },
      { name: 'BVM 676', automatMarkId: 16 },
      { name: 'BVM 681', automatMarkId: 16 },
      { name: 'BVM 695/3', automatMarkId: 16 },
      { name: 'BVM 901 LEIsa', automatMarkId: 16 },
      { name: 'BVM 951', automatMarkId: 16 },
      { name: 'BVM 952', automatMarkId: 16 },
      { name: 'BVM 972', automatMarkId: 16 },
      { name: 'Gaia', automatMarkId: 16 },
      { name: 'Gaia Style', automatMarkId: 16 },
      { name: 'Iris', automatMarkId: 16 },
      { name: 'LEI 400', automatMarkId: 16 },
      { name: 'LEI 600', automatMarkId: 16 },
      { name: 'LEI 700', automatMarkId: 16 },
      { name: 'Chameleon', automatMarkId: 14 },
      { name: 'Excellence', automatMarkId: 36 },
      { name: 'Pitstart', automatMarkId: 20 },
      { name: 'Crane 167', automatMarkId: 35 },
      { name: 'Evolution', automatMarkId: 35 },
      { name: 'Merchant 6', automatMarkId: 35 },
      { name: 'DN 5800', automatMarkId: 19 },
      { name: 'Pepsi', automatMarkId: 19 },
      { name: 'Tru-vend', automatMarkId: 24 },
      { name: 'Duetto', automatMarkId: 37 },
      { name: 'FAS 400', automatMarkId: 37 },
      { name: 'FAS 500 T', automatMarkId: 37 },
      { name: 'Fashion 600 E6', automatMarkId: 37 },
      { name: 'FAST', automatMarkId: 37 },
      { name: 'FAST 900', automatMarkId: 37 },
      { name: 'FAST 1050', automatMarkId: 37 },
      { name: 'JUST NOW', automatMarkId: 37 },
      { name: 'Krystal', automatMarkId: 37 },
      { name: 'Perla', automatMarkId: 37 },
      { name: 'Scudo 1050', automatMarkId: 37 },
      { name: 'Fri-Z400', automatMarkId: 30 },
      { name: 'D-05WP25S5', automatMarkId: 13 },
      { name: 'D-05WP30S5', automatMarkId: 13 },
      { name: 'D-05WP30S6', automatMarkId: 13 },
      { name: 'D-05WP36S6', automatMarkId: 13 },
      { name: 'D-06WP25S5', automatMarkId: 13 },
      { name: 'D-06WP30S5', automatMarkId: 13 },
      { name: 'D-06WP30S6', automatMarkId: 13 },
      { name: 'D-06WP36S6', automatMarkId: 13 },
      { name: 'D-07WP30S5', automatMarkId: 13 },
      { name: 'D-07WP30S6', automatMarkId: 13 },
      { name: 'D-07WP36S6', automatMarkId: 13 },
      { name: 'D-08WP25S5', automatMarkId: 13 },
      { name: 'D-08WP30S5', automatMarkId: 13 },
      { name: 'D-08WP30S6', automatMarkId: 13 },
      { name: 'D-08WP36S6', automatMarkId: 13 },
      { name: 'D-09WP30S5', automatMarkId: 13 },
      { name: 'D-09WP30S6', automatMarkId: 13 },
      { name: 'CTG', automatMarkId: 6 },
      { name: 'CTG-TOUCH', automatMarkId: 6 },
      { name: 'DBX-400', automatMarkId: 7 },
      { name: 'DRX', automatMarkId: 7 },
      { name: 'DRX-50', automatMarkId: 7 },
      { name: 'C02', automatMarkId: 33 },
      { name: 'C03', automatMarkId: 33 },
      { name: 'C010', automatMarkId: 33 },
      { name: 'Bluetec G335', automatMarkId: 21 },
      { name: 'Bluetec G546', automatMarkId: 21 },
      { name: 'Cofemar BLUETEC G23', automatMarkId: 21 },
      { name: 'Coffeemar G250', automatMarkId: 21 },
      { name: 'Coffeemar G500', automatMarkId: 21 },
      { name: 'Coffeemar G535', automatMarkId: 21 },
      { name: 'Coffeemar G546', automatMarkId: 21 },
      { name: 'Gourmet', automatMarkId: 21 },
      { name: 'Vision Combo Plus', automatMarkId: 21 },
      { name: 'Vision Easy Combo', automatMarkId: 21 },
      { name: 'WE8', automatMarkId: 29 },
      { name: 'G654M12', automatMarkId: 18 },
      { name: 'D720', automatMarkId: 4 },
      { name: 'Astro', automatMarkId: 8 },
      { name: 'Brio', automatMarkId: 8 },
      { name: 'Canto', automatMarkId: 8 },
      { name: 'Colibri', automatMarkId: 8 },
      { name: 'Concerto', automatMarkId: 8 },
      { name: 'Diesis', automatMarkId: 8 },
      { name: 'Jazz', automatMarkId: 8 },
      { name: 'Karisma', automatMarkId: 8 },
      { name: 'Kikko ES6', automatMarkId: 8 },
      { name: 'Kikko IN7', automatMarkId: 8 },
      { name: 'Kikko LB', automatMarkId: 8 },
      { name: 'Kikko Max', automatMarkId: 8 },
      { name: 'Kikko Max To Go', automatMarkId: 8 },
      { name: 'Korinto', automatMarkId: 8 },
      { name: 'Koro Prime', automatMarkId: 8 },
      { name: 'Melodia', automatMarkId: 8 },
      { name: 'Melodia SL', automatMarkId: 8 },
      { name: 'Opera', automatMarkId: 8 },
      { name: 'Rondo', automatMarkId: 8 },
      { name: 'Samba', automatMarkId: 8 },
      { name: 'Sfera', automatMarkId: 8 },
      { name: 'Snakky', automatMarkId: 8 },
      { name: 'Snakky 6-30', automatMarkId: 8 },
      { name: 'Snakky LX', automatMarkId: 8 },
      { name: 'Snakky Max', automatMarkId: 8 },
      { name: 'Snakky SL', automatMarkId: 8 },
      { name: 'Solista', automatMarkId: 8 },
      { name: 'Tango', automatMarkId: 8 },
      { name: 'Venezia LX', automatMarkId: 8 },
      { name: 'Zenith', automatMarkId: 8 },
      { name: 'Zeta', automatMarkId: 8 },
      { name: 'CS220', automatMarkId: 15 },
      { name: 'Zenius', automatMarkId: 15 },
      { name: 'Nova', automatMarkId: 25 },
      { name: 'P90', automatMarkId: 27 },
      { name: 'OR70', automatMarkId: 1 },
      { name: 'OR100', automatMarkId: 1 },
      { name: 'OR130', automatMarkId: 1 },
      { name: 'Caffè Europa', automatMarkId: 39 },
      { name: 'Cino EC E3', automatMarkId: 39 },
      { name: 'Cino EC E3 Pro', automatMarkId: 39 },
      { name: 'Cino XS Grande E5', automatMarkId: 39 },
      { name: 'Cino XS Grande Pro', automatMarkId: 39 },
      { name: 'Cino XS Grande VHO', automatMarkId: 39 },
      { name: 'Damian', automatMarkId: 39 },
      { name: 'LaRhea BL eC', automatMarkId: 39 },
      { name: 'LaRhea BL grande', automatMarkId: 39 },
      { name: 'laRhea Business line Grande VHO', automatMarkId: 39 },
      { name: 'LaRhea grande TV', automatMarkId: 39 },
      { name: 'Lazio E5', automatMarkId: 39 },
      { name: 'Luce E5', automatMarkId: 39 },
      { name: 'Luce E6', automatMarkId: 39 },
      { name: 'Luce Snack', automatMarkId: 39 },
      { name: 'Luce X', automatMarkId: 39 },
      { name: 'Luce X Snack', automatMarkId: 39 },
      { name: 'Luce X2', automatMarkId: 39 },
      { name: 'Luce X2 Pro', automatMarkId: 39 },
      { name: 'Luce X2 TouchTV', automatMarkId: 39 },
      { name: 'Sagoma Europa', automatMarkId: 39 },
      { name: 'Sagoma H6', automatMarkId: 39 },
      { name: 'Sagoma H7', automatMarkId: 39 },
      { name: 'Sagoma H8', automatMarkId: 39 },
      { name: 'Sagoma Luce', automatMarkId: 39 },
      { name: 'Sagoma Milano', automatMarkId: 39 },
      { name: 'Snack Europa', automatMarkId: 39 },
      { name: 'XTRA', automatMarkId: 39 },
      { name: 'Aliseo', automatMarkId: 23 },
      { name: 'Atlante 500', automatMarkId: 23 },
      { name: 'Corallo 1700', automatMarkId: 23 },
      { name: 'Cristallo 400', automatMarkId: 23 },
      { name: 'Cristallo 400 EVO', automatMarkId: 23 },
      { name: 'Cristallo 600', automatMarkId: 23 },
      { name: 'Diamante', automatMarkId: 23 },
      { name: 'MegaCold Slave', automatMarkId: 23 },
      { name: 'Phedra Espresso', automatMarkId: 23 },
      { name: 'Phedra EVO Espresso', automatMarkId: 23 },
      { name: 'Royal Prof', automatMarkId: 23 },
      { name: 'Rubino 200', automatMarkId: 23 },
      { name: 'Smeraldo 36/56', automatMarkId: 23 },
      { name: '217', automatMarkId: 38 },
      { name: '811', automatMarkId: 38 },
      { name: 'G-Snack', automatMarkId: 38 },
      { name: 'SVE DR9', automatMarkId: 38 },
      { name: 'SVE DV9', automatMarkId: 38 },
      { name: 'V-680', automatMarkId: 38 },
      { name: 'V21', automatMarkId: 38 },
      { name: 'Coffee Vito', automatMarkId: 11 },
      { name: 'Shaker-M', automatMarkId: 28 },
      { name: 'PSL1000', automatMarkId: 34 },
      { name: 'VM16', automatMarkId: 31 },
      { name: 'FoodBox', automatMarkId: 5 },
      { name: 'FoodBox Long', automatMarkId: 5 },
      { name: 'Nero', automatMarkId: 5 },
      { name: 'Nova', automatMarkId: 5 },
      { name: 'NovaBar', automatMarkId: 5 },
      { name: 'Rosso', automatMarkId: 5 },
      { name: 'ROSSO STREET', automatMarkId: 5 },
      { name: 'RossoBar', automatMarkId: 5 },
      { name: 'VS-21 HotCup', automatMarkId: 32 },
      { name: '1800 S', automatMarkId: 17 },
      { name: 'Presto', automatMarkId: 17 },
      { name: 'W700', automatMarkId: 22 },
      { name: 'W850', automatMarkId: 22 },
      { name: 'W1000', automatMarkId: 22 },
      { name: 'Акваматик', automatMarkId: 12 },
      { name: 'Мини', automatMarkId: 9 },
      { name: 'Стандарт', automatMarkId: 9 },
      { name: '500 (незамерзайка)', automatMarkId: 26 },
      { name: 'АТ-101/А', automatMarkId: 26 },
      { name: 'Вита (бытовая модель)', automatMarkId: 26 },
      { name: 'Рио (для продажи сока)', automatMarkId: 26 },
      { name: 'Оптима', automatMarkId: 3 },
      { name: 'Принт', automatMarkId: 3 },
      { name: 'Профи', automatMarkId: 3 },
    ])
  }
}
